name: "setup-poetry-env"
description: 'Sets up Python and Poetry with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}

  - name: Install Poetry
    uses: snok/install-poetry@v1
    with:
      version: latest
      virtualenvs-create: true
      virtualenvs-in-project: true

  - name: Cache Poetry dependencies
    uses: actions/cache@v3
    with:
      path: |
        .venv
        ~/.cache/pypoetry
        ~/.cache/pip
      key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/poetry.toml') }}
      restore-keys: |
        ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-
        ${{ runner.os }}-poetry-

  - name: Install dependencies
    run: poetry install --no-interaction
    shell: bash
