name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup the environment
      uses: ./.github/actions/setup-poetry-env

    - name: Run checks
      run: make check

    - name: Run tests
      run: make test
